Repository kubernetes-sigs/lwkd, pull requests merged in 2022-04, with the labels that each got.

#139 Week Ending April 3, 2022
  _posts/2022-04-03-update.md
Labels: size/M, cncf-cla: yes, approved

#140 Week Ending April 10, 2022
  _posts/2022-04-10-update.md
Labels: size/M, cncf-cla: yes, approved

#142 Update 2022-04-17-update.md
  _posts/2022-04-17-update.md
Labels: cncf-cla: yes, size/XS

#143 Week Ending April 17, 2022
  _posts/2022-04-17-update.md
  authors.md
Labels: size/M, cncf-cla: yes, approved

#144 Publish April 24th Edition
  _posts/2022-04-24-update.md
Labels: cncf-cla: yes
