Repository kubernetes-sigs/lwkd, pull requests merged in 2023-09, with the labels that each got.

#224 Added subprojects updates, developer news and misc. PRs for 09/03 issue
  _posts/2023-09-03-update.md
Labels: cncf-cla: yes, size/S, approved

#225 Added KEP of the Week, Release Schedule for 09/03 issue
  _posts/2023-09-03-update.md
Labels: cncf-cla: yes, size/S, approved

#227 Merge all changes, final 9/03 Text
  _posts/2023-09-03-update.md
Labels: cncf-cla: yes, approved

#228 Added KEP of the week for 09/10 issue
  _posts/2023-09-10-update.md
Labels: size/M, cncf-cla: yes, lgtm, approved

#229 Added subproject updates for 09/10 issue
  _posts/2023-09-10-update.md
Labels: cncf-cla: yes, size/XS, approved

#231 Week Ending September 10, 2023
  _posts/2023-09-10-update.md
Labels: size/M, cncf-cla: yes, approved

#234 Added 09/17 issue
  _posts/2023-09-17-update.md
  script.sh
Labels: size/M, cncf-cla: yes

#235 Week Ending September 17, 2023
  _posts/2023-09-17-update.md
  script.sh
Labels: size/M, cncf-cla: yes, approved

#237 Fix typo in 2023-09-17
  _posts/2023-09-17-update.md
Labels: cncf-cla: yes, size/XS

#236 Added release schedule for 09/24 issue
  _posts/2023-09-24-update.md
Labels: size/M, cncf-cla: yes, approved

#239 Added KEP of the week for 9/24 issue
  _posts/2023-09-24-update.md
Labels: cncf-cla: yes, size/XS

#238 Updated Release Schedule to latest information for 09/24 issue
  _posts/2023-09-24-update.md
Labels: cncf-cla: yes, size/XS

#240 Week Ending September 24, 2023
  _posts/2023-09-24-update.md
Labels: size/M, cncf-cla: yes, approved

#221 Updated OWNERS.
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S, approved
