Repository kubernetes-sigs/lwkd, pull requests merged in 2023-10, with the labels that each got.

#233 Issue Template for LWKD Newsletter update request
  .github/ISSUE_TEMPLATE/lwkd-report.md
Labels: size/M, cncf-cla: yes

#230 Added KEP of the week and subproject updates to template.md
  template.md
Labels: cncf-cla: yes, size/XS

#243 Added KEP of the week for 10/01 issue
  .github/ISSUE_TEMPLATE/lwkd-report.md
  OWNERS_ALIASES
  _posts/2023-10-01-update.md
  template.md
Labels: size/M, cncf-cla: yes, approved

#244 10/01 edition
  _posts/2023-10-01-update.md
Labels: size/M, cncf-cla: yes, approved

#242 Add Release Schedule and dev news for 08/10 issue
  _posts/2023-10-08-update.md
Labels: size/M, cncf-cla: yes, approved

#245 Added KEP of the week for 10/08 issue
  _posts/2023-10-08-update.md
Labels: cncf-cla: yes, size/XS, approved

#246 Week Ending October 08, 2023
  _posts/2023-10-08-update.md
Labels: size/M, cncf-cla: yes, approved

#241 Add Fyka to OWNERS so that she can create branches too.
  CONTRIBUTING.md
  OWNERS_ALIASES
  authors.md
Labels: cncf-cla: yes, size/XS, approved

#247 adding a slight update to release schedule for issue 17 Oct
  _posts/2023-10-15-update.md
Labels: cncf-cla: yes, size/XS

#248 Added KEP of the week for 10/15 issue
  _posts/2023-10-15-update.md
Labels: cncf-cla: yes, size/XS, approved

#249 Publish 10/15
  _posts/2023-10-15-update.md
Labels: size/M, cncf-cla: yes, approved

#251 Added Developer News, Release Schedule and other merges for 10/22 issue
  _posts/2023-10-22-update.md
Labels: size/M, cncf-cla: yes, approved

#253 Publish 10/22 edition
  _posts/2023-10-22-update.md
Labels: size/M, cncf-cla: yes, approved

#254 Add link to Summit sign-up sheet
  _posts/2023-10-22-update.md
Labels: cncf-cla: yes, size/XS, approved

#255 Added release sched, dev news for 10/29 issue
  _posts/2023-10-29-update.md
Labels: cncf-cla: yes, size/S, approved
