Repository kubernetes-sigs/lwkd, pull requests merged in 2023-11, with the labels that each got.

#256 Week Ending October 29, 2023
  _posts/2023-10-29-update.md
Labels: cncf-cla: yes, size/L, approved

#257 Week Ending November 5, 2023
  _posts/2023-11-05-update.md
Labels: size/M, cncf-cla: yes, approved

#258 feat: add featured PR section for LWKD - Nov 12
  _posts/2023-11-12-update.md
Labels: cncf-cla: yes, size/XS

#259 Publish 11/12
  _posts/2023-11-12-update.md
Labels: cncf-cla: yes, approved

#260 Added Developer News, Release Schedule for 11/19 issue
  _posts/2023-11-19-update.md
Labels: size/M, cncf-cla: yes, approved

#261 Publish 11/19 edition
  _posts/2023-11-19-update.md
Labels: size/M, cncf-cla: yes, approved

#262 Fix link to KubeWeekly
  index.md
Labels: cncf-cla: yes, size/XS, approved

#263 Added template for 26/11
  _posts/2023-11-26-update.md
Labels: size/M, cncf-cla: yes, approved

#264 Publish 11/26 edition
  _posts/2023-11-26-update.md
Labels: size/M, cncf-cla: yes, approved
