Repository kubernetes-sigs/lwkd, pull requests merged in 2023-12, with the labels that each got.

#265 Add info on where to find Developer News
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/S, approved

#269 Add Script Release Crawler
  scripts/release-crawler/README.md
  scripts/release-crawler/go.mod
  scripts/release-crawler/main.go
  scripts/release-crawler/template.html
Labels: cncf-cla: yes, size/L

#271 Added release schedule for 12/10
  _posts/2023-12-10-update.md
Labels: size/M, cncf-cla: yes, needs-rebase, approved

#272 December 10 Edition
  _posts/2023-12-10-update.md
Labels: size/M, cncf-cla: yes, approved

#275 Add Github Actions for running crawler automatically
  .github/workflows/get-releases-weekly.yaml
  scripts/release-crawler/go.mod
  scripts/release-crawler/go.sum
  scripts/release-crawler/main.go
  scripts/release-crawler/release-notes-html/.gitkeep
  scripts/release-crawler/release-notes-md/.gitkeep
Labels: cncf-cla: yes, size/L

#273 Correct typo from 'kubenetes' to 'kubernetes'
  _posts/2018-12-02-update.md
Labels: cncf-cla: yes, size/XS

#276 Publish 12/17 edition
  _posts/2023-12-17-update.md
Labels: cncf-cla: yes, approved

#278 dev news and release sched for 12/24
  _posts/2023-12-24-update.md
Labels: cncf-cla: yes, size/XS, approved

#277 Publish 12/24 edition
  _posts/2023-12-24-update.md
Labels: size/M, cncf-cla: yes, approved

#280 Fixed date for 12/24 issue
  _posts/2023-12-24-update.md
Labels: cncf-cla: yes, approved

#281 Fixed timestamp for 12/24
  _posts/2023-12-24-update.md
Labels: cncf-cla: yes, size/XS, approved

#279 Change github action to create a PR for related project releases
  .github/workflows/get-releases-weekly.yaml
Labels: cncf-cla: yes, size/S
