Repository kubernetes-sigs/lwkd, pull requests merged in 2023-08, with the labels that each got.

#211 Added KEP of the week
  _posts/2023-07-30-update.md
Labels: cncf-cla: yes, size/XS

#212 Publish 7/30 edition
  _posts/2023-07-30-update.md
Labels: size/M, cncf-cla: yes, approved

#213 Initial draft for 8/06 issue
  _posts/2023-08-06-update.md
Labels: size/M, cncf-cla: yes, approved

#214 Publish August 6 edition
  _posts/2023-08-06-update.md
  authors.md
Labels: cncf-cla: yes, approved

#216 fix broken links to testgrid dashboard
  _posts/2018-08-12-update.md
  _posts/2018-08-19-update.md
  _posts/2018-08-26-update.md
  _posts/2022-11-20-update.md
Labels: cncf-cla: yes, size/XS

#218 Publish 8/13 edition
  _posts/2023-08-13-update.md
Labels: cncf-cla: yes, approved

#219 Added KEP of the week
  _posts/2023-08-20-update.md
Labels: cncf-cla: yes, size/XS

#220 Publish 8/20 edition
  _posts/2023-08-20-update.md
Labels: cncf-cla: yes, approved

#222 Added KEP of the Week and subproject updates for 08/27 issue
  _posts/2023-08-27-update.md
Labels: cncf-cla: yes, size/S

#223 Week Ending August 27, 2023
  _posts/2023-08-27-update.md
Labels: size/M, cncf-cla: yes, approved
