Repository kubernetes-sigs/lwkd, pull requests merged in 2024-01, with the labels that each got.

#284 Replace deprecated command with environment file
  .github/workflows/get-releases-weekly.yaml
Labels: cncf-cla: yes, size/XS, lgtm

#286 Add Project updates
  _posts/2024-01-07-update.md
  scripts/release-crawler/release-notes-html/2023-12-25.html
  scripts/release-crawler/release-notes-md/2023-12-25.md
Labels: size/M, cncf-cla: yes, approved

#287 KEP: Allow informers for getting a stream of data instead of chunking for 07 January 2024
  _posts/2024-01-07-update.md
Labels: cncf-cla: yes, size/XS, approved

#288 Publish 01/07 edition
  _posts/2024-01-07-update.md
  template.md
Labels: size/M, cncf-cla: yes, approved

#289 Fixing utc time for re-running jobs
  _posts/2024-01-07-update.md
Labels: cncf-cla: yes, size/XS, approved

#291 Add Kubespray to Project Update
  scripts/release-crawler/README.md
  scripts/release-crawler/main.go
Labels: cncf-cla: yes, size/XS

#293 Add legacy repository reminder & subproject updates to 20240114
  _posts/2024-01-14-update.md
Labels: size/M, cncf-cla: yes

#294 Add additional repositories - optimize Output for crawler
  scripts/release-crawler/main.go
Labels: size/M, cncf-cla: yes, approved

#297 Publish 21 Jan 2024 edition
  _posts/2024-01-21-update.md
Labels: size/M, cncf-cla: yes, approved

#299 Publish 01/21 issue
  _posts/2024-01-21-update.md
Labels: size/M, cncf-cla: yes, approved

#301 Add Contributor Summit updates
  _posts/2024-01-28-update.md
Labels: cncf-cla: yes, size/XS

#303 Release Schedule and Dev News for 28 Jan issue
  _posts/2024-01-28-update.md
Labels: cncf-cla: yes, size/XS, approved

#302 Added other merges, promotions and deprecations
  _posts/2024-01-28-update.md
Labels: cncf-cla: yes, size/S, approved

#304 Publish Jan 28
  _posts/2024-01-28-update.md
Labels: size/M, cncf-cla: yes, approved
