Repository kubernetes-sigs/lwkd, pull requests merged in 2024-06, with the labels that each got.

#371 Subprojects and Dependency Updates 02062024
  _posts/2024-06-02-update.md
Labels: cncf-cla: yes, size/XS, approved

#373 featured PRs: 2-june-2024
  _posts/2024-06-02-update.md
  scripts/release-crawler/release-notes-html/2024-05-20.html
  scripts/release-crawler/release-notes-html/2024-05-27.html
  scripts/release-crawler/release-notes-md/2024-05-20.md
  scripts/release-crawler/release-notes-md/2024-05-27.md
Labels: cncf-cla: yes, size/XXL, approved

#370 Publish 06/02 issue
  .DS_Store
  _posts/2024-06-02-update.md
Labels: size/M, cncf-cla: yes, approved

#377 featured pr 06/09
  _posts/2024-06-09-update.md
Labels: cncf-cla: yes, size/XS, approved

#379 Added other merges
  _posts/2024-06-09-update.md
Labels: cncf-cla: yes, size/S, approved

#378 Update 2024-06-09-update.md
  _posts/2024-06-09-update.md
Labels: cncf-cla: yes, size/XS

#375 Publish 06/09
  _posts/2024-06-09-update.md
Labels: size/M, cncf-cla: yes, approved

#372 Add draft stylesheet info for subprojects.
  STYLESHEET.md
Labels: cncf-cla: yes, size/S, approved

#380 [Week Ending June 9, 2024] fix links in section - other merges
  _posts/2024-06-09-update.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#384 add Subprojects and Dependency Updates for 06162024
  _posts/2024-06-16-update.md
Labels: cncf-cla: yes, size/XS, approved

#385 add release sched, featured pr: 18/06
  _posts/2024-06-16-update.md
Labels: cncf-cla: yes, size/S, approved

#387 Publish 6/16
  _posts/2024-06-16-update.md
Labels: cncf-cla: yes, approved

#389 Add project adjecent project updates
  _posts/2026-06-23-update.md
Labels: cncf-cla: yes, size/XS, approved

#390 Update 2026-06-23-update.md
  _posts/2026-06-23-update.md
Labels: cncf-cla: yes, size/XS

#393 featured PR: [Add field management support to fake client-go typed client]
  _posts/.2024-06-16-update.md.swp
  _posts/2024-06-23-update.md
  scripts/release-crawler/release-notes-html/2024-06-17.html
  scripts/release-crawler/release-notes-md/2024-06-17.md
Labels: cncf-cla: no, size/L, approved

#391 Publish 06/23 issue
  _posts/.2024-06-16-update.md.swp
  _posts/2024-06-23-update.md
Labels: size/M, cncf-cla: no, approved
