Repository kubernetes-sigs/lwkd, pull requests merged in 2024-04, with the labels that each got.

#338 Add updates of subproject and sig release survey
  _posts/2024-03-31-update.md
Labels: cncf-cla: yes, size/XS, approved

#337 Publish 03/31 issue
  _posts/2024-03-31-update.md
Labels: size/M, cncf-cla: yes, approved

#341 Add Adjecent Project updates & Video News for 04072024
  _posts/2024-04-07-update.md
Labels: cncf-cla: yes, size/XS, approved

#340 Publish 04/07 issue
  _posts/2024-04-07-update.md
Labels: size/M, cncf-cla: yes, lgtm, approved

#345 Added KEP section
  _posts/2024-04-14-update.md
Labels: cncf-cla: yes, size/XS, approved

#343 Publish 04/14 issue
  _posts/2024-04-14-update.md
Labels: size/M, cncf-cla: yes, approved

#348 Added KEP of the week, dev news and release schedule for 04/21 issue
  _posts/2024-04-21-update.md
Labels: size/M, cncf-cla: yes, approved

#349 Publish 4/21 Edition
  _posts/2024-04-21-update.md
Labels: size/M, cncf-cla: yes, approved

#351 Added the KEP section for 280424
  _posts/2024-04-28-update.md
Labels: cncf-cla: yes, size/XS
