Repository kubernetes-sigs/lwkd, pull requests merged in 2024-05, with the labels that each got.

#352 Publish 4.28
  _posts/2024-04-28-update.md
Labels: cncf-cla: yes, approved

#354 adjecent Projekt updates for 05052024
  _posts/2024-05-05-update.md
Labels: cncf-cla: yes, size/XS, approved

#355 Publish 05/05 issue
  _posts/2024-05-05-update.md
Labels: size/M, cncf-cla: yes, approved

#358 Add Dev updates and related projects
  _posts/2024-05-12-update.md
Labels: cncf-cla: yes, size/S, approved

#357 Publish 05/12 issue
  _posts/2024-05-12-update.md
Labels: size/M, cncf-cla: yes, approved

#359 Fix time in 05/12 issue
  _posts/2024-05-12-update.md
Labels: cncf-cla: yes, approved

#362 add: release sched, dev news | 19 May 2024
  _posts/2024-05-19-update.md
Labels: cncf-cla: yes, approved

#363 Add KEP 4568 & Subprojects and Dependency Updates for 20240519
  _posts/2024-05-19-update.md
Labels: cncf-cla: yes, size/S, approved

#361 Publish 05/19
  _posts/2024-05-19-update.md
Labels: size/M, cncf-cla: yes, approved

#366 Other merges added
  _posts/2024-05-26-update.md
Labels: size/M, cncf-cla: yes

#368 add Subprojects and Dependency Updates
  _posts/2024-05-26-update.md
Labels: cncf-cla: yes, size/XS, approved

#367 05/26 release updates
  _posts/2024-05-26-update.md
Labels: cncf-cla: yes, size/XS, approved

#365 Publish 05/26 issue
  _posts/2024-05-26-update.md
Labels: size/M, cncf-cla: yes, approved
