Repository kubernetes-sigs/lwkd, pull requests merged in 2024-07, with the labels that each got.

#392 update contribex leads owners
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved

#397 featured pr: kubeadm: enable the v1beta4 API | 30jun2024 edition
  _posts/2024-06-30-update.md
Labels: cncf-cla: yes, size/XS, approved

#396 Add dev news on a branch in order to document how it gets there.
  _posts/2024-06-30-update.md
Labels: cncf-cla: yes, size/XS, approved

#395 Publish 6/30 issue
  _posts/2024-06-30-update.md
Labels: size/M, cncf-cla: yes, do-not-merge/hold, approved

#399 Publish 07/07 issue
  _posts/2024-07-07-update.md
Labels: size/M, cncf-cla: yes, approved

#401 Publish 7/14 edition
  _posts/2024-07-14-update.md
Labels: size/M, cncf-cla: yes, approved

#404 featured PR 24072024
  _posts/2024-07-21-update.md
Labels: cncf-cla: yes, size/XS, approved

#405 Update 2024-07-21-update.md
  _posts/2024-07-21-update.md
Labels: cncf-cla: yes, size/XS

#403 Publish 07/21 issue
  _posts/2024-07-21-update.md
Labels: size/M, cncf-cla: yes, approved

#406 chore: rm .DS_Store
  .DS_Store
Labels: cncf-cla: yes, size/XS, kind/cleanup

#409 Patch 2
  _posts/2024-07-28-update.md
Labels: cncf-cla: yes, size/XS

#410 Update 2024-07-28-update.md
  _posts/2024-07-28-update.md
Labels: cncf-cla: yes, size/XS

#408 Publish 07/28 issue
  _posts/.2024-06-16-update.md.swp
  _posts/2024-07-28-update.md
Labels: size/M, cncf-cla: yes, approved
