Repository kubernetes-sigs/lwkd, pull requests merged in 2025-05, with the labels that each got.

#504 Add Featured PRs for 20250504 lwkd
  _posts/2025-05-04-update.md
Labels: cncf-cla: yes, size/S

#505 Dev News Week of May 4th
  _posts/2025-05-04-update.md
Labels: cncf-cla: yes, size/XS

#503 Publish 05/04 issue
  _posts/2025-05-04-update.md
Labels: size/M, cncf-cla: yes, approved

#507 Dev News 20250511
  _posts/2025-05-11-update.md
Labels: cncf-cla: yes, size/XS

#508 Added featured PRs for 20250511 lwkd
  _posts/2025-05-11-update.md
Labels: cncf-cla: yes, size/XS

#509 Publish 5/11
  _posts/2025-05-11-update.md
Labels: cncf-cla: yes, approved

#511 Dev News May 19 2025
  _posts/2025-05-18-update.md
Labels: cncf-cla: yes, size/S

#512 added etcd release under SubProjects
  _posts/2025-05-18-update.md
Labels: cncf-cla: yes, size/XS

#513 Added featured PRs for 20250518 lwkd
  _posts/2025-05-18-update.md
Labels: cncf-cla: yes, size/XS, approved

#514 Update 2025-05-18-update.md
  _posts/2025-05-18-update.md
Labels: cncf-cla: yes, size/XS

#510 Publish 5/18 issue
  _posts/2025-05-18-update.md
Labels: size/M, cncf-cla: yes, approved

#515 Fixed date
  _posts/2025-05-18-update.md
Labels: cncf-cla: yes, approved

#516 Add the autoscaler repo
  scripts/release-crawler/main.go
Labels: cncf-cla: yes, size/XS, lgtm, approved

#520 Dev News for week of May 25
  _posts/2025-05-25-update.md
Labels: cncf-cla: yes, size/XS

#522 KEP
  _posts/2025-05-25-update.md
Labels: cncf-cla: yes, size/XS

#519 Added pre-commit script to automate setting date in posts
  pre-commit.sh
Labels: cncf-cla: yes, size/S, approved

#517 Publish 5/25 issue
  _posts/2025-05-25-update.md
Labels: size/M, cncf-cla: yes, approved
