Repository kubernetes-sigs/lwkd, pull requests merged in 2025-02, with the labels that each got.

#480 featured PR: Improve SA max token expiry with external signer logic, and plumb extended expiry duration
  _posts/2025-02-02-update.md
Labels: cncf-cla: yes, size/XS, approved

#479 Publish 2/2
  _posts/2025-02-02-update.md
Labels: size/M, cncf-cla: yes, approved

#481 Publish 02/09 issue
  _posts/2025-02-09-update.md
Labels: size/M, cncf-cla: yes, approved

#483 Update 2025-02-16-update.md
  _posts/2025-02-16-update.md
Labels: cncf-cla: yes, size/XS

#482 Publish 02/16 issue
  _posts/2025-02-16-update.md
Labels: size/M, cncf-cla: yes, approved

#484 Update 2025-02-23-update.md
  _posts/2025-02-23-update.md
Labels: cncf-cla: yes, size/XS

#485 Publish 2/23
  _posts/2025-02-23-update.md
Labels: size/M, cncf-cla: yes, approved
