Repository kubernetes-sigs/lwkd, pull requests merged in 2025-08, with the labels that each got.

#588 minor spell check
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#590 PR for shoutouts 2025-08-10
  _posts/2025-08-10-update.md
Labels: cncf-cla: yes, size/XS

#591 Dev News 2025-08-10-update.md
  _posts/2025-08-10-update.md
Labels: cncf-cla: yes, size/XS

#592 Subprojects and Dependency Updates for 2025-08-10
  _posts/2025-08-10-update.md
Labels: cncf-cla: yes

#593 update other merges
  _posts/2025-08-10-update.md
Labels: cncf-cla: yes, size/XS

#594 add: release updates for 20250810
  _posts/2025-08-10-update.md
Labels: cncf-cla: yes, size/XS

#595 publish 8.10
  _posts/2025-08-10-update.md
Labels: size/M, cncf-cla: yes, approved

#597 shoutouts for 2025-08-17
  _posts/2025-08-17-update.md
Labels: cncf-cla: yes, size/XS

#596 update other merges
  _posts/2025-08-17-update.md
Labels: cncf-cla: yes, size/S, approved

#599 Subprojects and Dependency updates for 2025-08-17
  _posts/2025-08-17-update.md
Labels: cncf-cla: yes, size/XS, approved

#600 Add/release schedule 20250817
  _posts/2025-08-17-update.md
Labels: cncf-cla: yes, size/XS

#601 KEP
  _posts/2025-08-17-update.md
Labels: cncf-cla: yes, size/XS

#603 Publish 8.17
  _posts/2025-08-17-update.md
Labels: size/M, cncf-cla: yes, approved

#607 KEP
  _posts/2025-08-24-update.md
Labels: cncf-cla: yes, size/XS

#608 Subprojects and Dependency updates 2025-08-24
  _posts/2025-08-24-update.md
Labels: cncf-cla: yes, size/XS

#611 featured pr for 20250824
  _posts/2025-08-24-update.md
Labels: cncf-cla: yes, size/XS

#612 Dev News 2025-08-24-update.md
  _posts/2025-08-24-update.md
Labels: cncf-cla: yes, size/XS

#604 Publish 8/24 issue
  _posts/2025-08-24-update.md
Labels: size/M, cncf-cla: yes, approved
