Repository kubernetes-sigs/lwkd, pull requests merged in 2025-06, with the labels that each got.

#527 Dev News
  _posts/2025-06-01-update.md
Labels: cncf-cla: yes, size/XS

#530 Shoutouts for 2025-06-08-update.md
  _posts/2025-06-08-update.md
Labels: cncf-cla: yes, size/XS

#532 Subproject and Dependency updates for 20250608
  _posts/2025-06-08-update.md
Labels: cncf-cla: yes, size/XS

#533 Dev News
  _posts/2025-06-08-update.md
Labels: cncf-cla: yes, size/XS

#528 Publish 6/8 issue
  _posts/2025-06-08-update.md
  scripts/release-crawler/release-notes-html/2025-06-11.html
  scripts/release-crawler/release-notes-md/2025-06-11.md
Labels: cncf-cla: yes, size/XL, approved

#534 Fix KEP-3015 description in 2025-06-08-update.md
  _posts/2025-06-08-update.md
Labels: cncf-cla: yes, size/XS

#536 Subprojects and Depedency update for 2025-06-15-update.md
  _posts/2025-06-15-update.md
Labels: cncf-cla: yes, size/XS

#535 KEP
  _posts/2025-06-15-update.md
Labels: cncf-cla: yes, size/XS, approved

#539 featured PRs for 20250615
  _posts/2025-06-15-update.md
Labels: cncf-cla: yes, size/XS, approved

#538 Dev News
  _posts/2025-06-15-update.md
Labels: cncf-cla: yes, size/XS, approved

#540 Publish 6/15
  _posts/2025-06-15-update.md
Labels: size/M, cncf-cla: yes, approved

#546 Update 2025-06-22-update.md
  _posts/2025-06-22-update.md
Labels: cncf-cla: yes, size/XS, approved
