Repository kubernetes-sigs/lwkd, pull requests merged in 2025-04, with the labels that each got.

#492 Publish 04/06 issue
  _posts/2025-04-06-update.md
Labels: size/M, cncf-cla: yes, approved

#493 Fixed typo
  _posts/2025-04-06-update.md
Labels: cncf-cla: yes, size/XS, approved

#494 Update 2025-04-13-update.md
  _posts/2025-04-13-update.md
Labels: cncf-cla: yes, size/XS

#495 Added information about Release Schedule for upcoming 20250413 LWKD
  _posts/2025-04-13-update.md
Labels: cncf-cla: yes, size/XS

#496 publish 4.13
  _posts/2025-04-13-update.md
Labels: size/M, cncf-cla: yes, approved

#497 Publish 4/20 issue
  _posts/2025-04-20-update.md
Labels: size/M, cncf-cla: yes, approved

#501 Added featured PRs for 4/27 issue
  _posts/2025-04-27-update.md
Labels: cncf-cla: yes, size/S, approved

#500 KEP
  _posts/2025-04-27-update.md
Labels: cncf-cla: yes, size/XS, approved

#499 Added develoepr news for LWKD
  _posts/2025-04-27-update.md
Labels: cncf-cla: yes, size/S, approved

#498 Publish 4/27 issue
  _posts/2025-04-27-update.md
Labels: size/M, cncf-cla: yes, approved
