Repository kubernetes-sigs/lwkd, pull requests merged in 2025-01, with the labels that each got.

#470 featured PR: Fix `PodTopologySpread` matching pods counts for constraints with the same topologyKey
  _posts/2025-01-05-update.md
Labels: cncf-cla: yes, size/XS, approved

#469 Publish 01/05
  _posts/2025-01-05-update.md
  template.md
Labels: size/M, cncf-cla: yes, approved

#471 Updated Bluesky link with new username
  _layouts/default.html
Labels: cncf-cla: yes, size/XS, approved

#472 Publish 01/12 issue
  _posts/2025-01-12-update.md
Labels: size/M, cncf-cla: yes, approved

#475 featured PR: DRA CEL- Add Missing Size Estimator
  _posts/2025-01-19-update.md
Labels: cncf-cla: yes, size/S, approved

#478 featured PR: add PodReplacementPolicy for Deployments: terminating pods
  _posts/2025-01-26-update.md
Labels: cncf-cla: yes, size/XS, approved

#477 Publish 01/26 issue
  _posts/2025-01-26-update.md
Labels: size/M, cncf-cla: yes, approved
