Repository kubernetes-sigs/lwkd, pull requests merged in 2025-09, with the labels that each got.

#617 update other merges
  _posts/2025-08-31-update.md
Labels: size/M, cncf-cla: yes

#618 shoutouts for 2025-08-31
  _posts/2025-08-31-update.md
Labels: cncf-cla: yes, size/S

#619 Dev News2025-08-31-update.md
  _posts/2025-08-31-update.md
Labels: cncf-cla: yes, size/XS

#620 Featured PRs for 20250831
  _posts/2025-08-31-update.md
Labels: cncf-cla: yes, size/S

#621 Subprojects and Dependency Updates 2025-08-31
  _posts/2025-08-31-update.md
Labels: cncf-cla: yes, size/S

#615 Publish 8/31 issue
  _posts/2025-08-31-update.md
Labels: cncf-cla: yes, size/L, approved

#633 add: release-schedule-20250914
  _posts/2025-09-14-update.md
Labels: cncf-cla: yes, needs-rebase, size/XS

#634 Subprojects and Dependency Update 2025-09-14
  _posts/2025-09-14-update.md
Labels: cncf-cla: yes, size/XS

#636 Publish 9/14
  _posts/2025-09-14-update.md
Labels: cncf-cla: yes, approved

#640 Subprojects and Dependency Updates 2025-09-21
  _posts/2025-09-21-update.md
Labels: cncf-cla: yes, size/XS, approved

#643 KEP 2025-09-28
  _posts/2025-09-28-update.md
Labels: cncf-cla: yes, size/XS, approved
