Repository kubernetes-sigs/lwkd, pull requests merged in 2025-07, with the labels that each got.

#550 Promotions and version updates for 6/29
  _posts/2025-06-29-update.md
Labels: cncf-cla: yes, size/XS, approved

#549 add: KEP of the week-2025-06-29
  _posts/2025-06-29-update.md
Labels: cncf-cla: yes, size/XS, approved

#551 featured PRs for 20250629 LWKD
  _posts/2025-06-29-update.md
Labels: cncf-cla: yes, size/XS, approved

#552 Shoutouts for 2025-06-29-update.md
  _posts/2025-06-29-update.md
Labels: cncf-cla: yes, size/XS

#562 Featured PRs for 20250706
  _posts/2025-07-06-update.md
Labels: cncf-cla: yes, size/XS, approved

#557 Release Schedule for 2025-07-06
  _posts/2025-07-06-update.md
Labels: cncf-cla: yes, size/XS

#564 General Merges for 2025-07-13-update.md
  _posts/2025-07-13-update.md
Labels: size/M, cncf-cla: yes

#565 Add/kep 20250713
  _posts/2025-07-13-update.md
Labels: cncf-cla: yes, size/XS

#566 featured pr for 20250713
  _posts/2025-07-13-update.md
Labels: cncf-cla: yes, size/S

#567 Release Updates for 2025-07-13
  _posts/2025-07-13-update.md
Labels: cncf-cla: yes, size/XS

#569 Publish 7/13
  _posts/2025-07-13-update.md
Labels: cncf-cla: yes, size/L, approved

#572 Dev News 2025-07-20-update.md
  _posts/2025-07-20-update.md
Labels: cncf-cla: yes, size/XS

#575 add: kep for 20250720
  _posts/2025-07-20-update.md
Labels: cncf-cla: yes, size/XS

#574 update Subprojects and Deps
  _posts/2025-07-20-update.md
Labels: cncf-cla: yes, size/XS

#573 General Merges for 2025-07-20-update.md
  _posts/2025-07-20-update.md
Labels: size/M, cncf-cla: yes, approved

#580 adding Subprojects and Dependency Updates and Shoutouts
  _posts/2025-07-27-update.md
Labels: cncf-cla: yes, size/XS

#581 Dev News 2025-07-27-update.md
  _posts/2025-07-27-update.md
Labels: cncf-cla: yes, size/XS, approved

#582 Featured PRs for 20250727
  _posts/2025-07-27-update.md
Labels: cncf-cla: yes, size/S, approved

#585 General Merges for 2025-07-27-update.md
  _posts/2025-07-27-update.md
Labels: size/M, cncf-cla: yes, approved
