Repository kubernetes-sigs/lwkd, pull requests merged in 2025-10, with the labels that each got.

#645 Subprojects and Dependency Updates 2025-09-28
  _posts/2025-09-28-update.md
Labels: cncf-cla: yes, size/S

#644 adding other merges
  _posts/2025-09-28-update.md
Labels: cncf-cla: yes, size/S

#641 Publish 9/28 issue
  _posts/2025-09-28-update.md
Labels: size/M, cncf-cla: yes, approved

#651 adding shoutouts
  _posts/2025-10-05-update.md
Labels: cncf-cla: yes, size/XS, approved
